### ISSUE TITLE
Supervised Clustering

### ISSUE THREAD

**Issue by seekingdeep** [wangyufeng111/pc_gain#1]
@wangyufeng111 
can pc_gain be used on tabular data to predict `cluster` for each row 
example

x | y | cluster
-- | -- | --
1221 | 267.5 | 1
1220 | 322.5 | 1
839.5 | 433.5 | 1
770.5 | 546 | 2
1213.5 | 661.5 | 3
1194 | 716.5 | 3
1164 | 771.5 | 3

**Comment by wangyufeng111** [comment]
I'm sorry I didn't see your email until now. It can only give approximate labels on the basis of pre-training some data, it's very fuzzy. Our model is designed to fill in missing data, so whether accurate labels can be obtained is not our concern.



At 2020-11-28 01:41:12, "seekingdeep" <notifications@github.com> wrote:

@wangyufeng111
can pc_gain be used on tabular data to predict cluster for each row
example

| x | y | cluster |
| 1221 | 267.5 | 1 |
| 1220 | 322.5 | 1 |
| 839.5 | 433.5 | 1 |
| 770.5 | 546 | 2 |
| 1213.5 | 661.5 | 3 |
| 1194 | 716.5 | 3 |
| 1164 | 771.5 | 3 |

**Comment by wangyufeng111** [comment]
I'm sorry I didn't see your email until now. It can only give approximate labels on the basis of pre-training some data, it's very fuzzy. Our model is designed to fill in missing data, so whether accurate labels can be obtained is not our concern.
